import type { Metadata } from 'next';
import Navbar from './Navbar';
import "public/css/all.min.css";
import "public/css/globals.css";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
